# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testPod

  target 'testPodTests' do
    inherit! :search_paths
    # Pods for testing

  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'AWSAPIGateway', '~> 2.4.7'
   pod 'OpenSSL-Universal', '~> 1.0'
  pod 'FMDB'
  end

end
